# Generated by Django 4.1 on 2022-09-05 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact_alter_category_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='heading',
            new_name='generic',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='content',
            new_name='paragraph',
        ),
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 22, 45, 7, 772424)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 22, 45, 7, 772424)),
        ),
    ]
